global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'leemons'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: local
          region: us-east-1
  - job_name: 'jaeger'
    scrape_interval: 5s
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          env: local
          region: us-east-1
  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:3030']
        labels:
          env: local
          region: eu-west-1
  - job_name: 'order'
    scrape_interval: 5s
    static_configs:
      - targets: ['orders:3030']
        labels:
          env: local
          region: eu-west-1
  - job_name: 'warehouse'
    scrape_interval: 5s
    static_configs:
      - targets: ['warehouse:3030']
        labels:
          env: local
          region: eu-west-1